packages:
  - 'apps/*'
  - 'packages/*'
  - 'supabase/functions/*'
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@sentry/cli': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  sharp: true
  unrs-resolver: true
