CREATE TABLE audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event TEXT NOT NULL,
  user_email TEXT,
  user_id UUID REFERENCES auth.users(id),
  ip_address TEXT,
  status TEXT NOT NULL, -- success, warning, danger
  details JSONB,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- RLS
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Superadmins can read audit_logs"
  ON audit_logs FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM profiles 
      WHERE profiles.id = auth.uid() AND profiles.is_superadmin = true
    )
  );

CREATE POLICY "System can insert audit_logs"
  ON audit_logs FOR INSERT
  WITH CHECK (true); -- Usually inserted from Edge Functions or backend routes (service role), but if from client, allow true or just let service role do it.
